### ISSUE TITLE
Error on : yo cc-angular:service my-service

### ISSUE THREAD

**Issue by cmelian** [leanovate/generator-cc-angular#3]
`/usr/local/lib/node_modules/yo/node_modules/inquirer/node_modules/rx/dist/rx.js:579
    throw e;
          ^`

`Error: Line 3: Unexpected token :
    at throwError (/usr/local/lib/node_modules/generator-cc-angular/node_modules/ng-parse-module/node_modules/esprima/esprima.js:1156:21)
    at throwUnexpected (/usr/local/lib/node_modules/generator-cc-angular/node_modules/ng-parse-module/node_modules/esprima/esprima.js:1213:9)
    at consumeSemicolon (/usr/local/lib/node_modules/generator-cc-angular/node_modules/ng-parse-module/node_modules/esprima/esprima.js:1295:13)
    at parseStatement (/usr/local/lib/node_modules/generator-cc-angular/node_modules/ng-parse-module/node_modules/esprima/esprima.js:2804:9)
    at /usr/local/lib/node_modules/generator-cc-angular/node_modules/ng-parse-module/node_modules/esprima/esprima.js:3609:38
    at parseStatement (/usr/local/lib/node_modules/generator-cc-angular/node_modules/ng-parse-module/node_modules/esprima/esprima.js:2794:27)
    at /usr/local/lib/node_modules/generator-cc-angular/node_modules/ng-parse-module/node_modules/esprima/esprima.js:3609:38
    at parseSourceElement%`

**Comment by AnBauer** [comment]
Do you use the latest version of cc-angular (1.0.2)? I tried both: adding the service to root module and a new one, both worked.

**Comment by cmelian** [comment]
I've just sees your answers in "grunt test - error #4". It is related. 
Will wait your next update.
Regards
